python3 layout_superstructure_detect.py input intermediate
python3 add_ocr_to_layout_jsons.py intermediate
python3 add_llm_cleaning_to_layout_jsons.py intermediate
python3 json_join_excel_export.py intermediate output/machines1935.xlsx