layout_superstructure_detect.py input intermediate
add_ocr_to_layout_jsons.py intermediate
add_llm_cleaning_to_layout_jsons.py intermediate
json_join_excel_export.py intermediate output/machines1935.xlsx